Feature/tf 733 brs linux64 build
ultraleap/TouchFree pull request #470
Opened 2023-03-15 12:01 UTC by GabrielHomewoodUL

## Summary

Update to build for more platforms

## Contributor Tasks

_These tasks are for the pull request creator to tick off._

- [ ] Relevant changelogs have been updated with user-visible changes
    - [ ] [TouchFree Windows](/ultraleap/touchfree/blob/-/CHANGELOG-windows.md)
    - [ ] [TouchFree BrightSign](/ultraleap/touchfree/blob/-/CHANGELOG-brightsign.md)
    - [ ] [TouchFree Web Tooling](/ultraleap/touchfree/blob/-/TF_Tooling_Web/CHANGELOG.md)

## Reviewer Tasks

_Add any instructions or tasks for the reviewer such as specific test considerations before this can be merged._

- [ ] Developer testing
- [x] Code reviewed
- [ ] Non-code assets reviewed
- [ ] Documentation reviewed - includes checking documentation requirements are met and not missing e.g., public API is commented

2023-03-15 16:58 UTC, DavidFee-UL requested changes

2023-03-15 16:58 UTC, DavidFee-UL commented on TF_Service_dotNet/TouchFree/TouchFreeLib.csproj
> +	</ItemGroup>
Is this a duplicate entry?

2023-03-15 16:58 UTC, DavidFee-UL commented on .gitlab-ci.yml
> +    - dotnet publish -p:BRIGHTSIGN=$BRIGHTSIGN -p:VersionPrefix=$TOUCHFREE_VERSION -p:VersionSuffix=$TOUCHFREE_SUFFIX -c Release -r $RUNTIME "$CI_PROJECT_DIR/TF_Service_dotNet/TouchFree/TouchFreeLib.
I can't find what the -p option does but I assume it's a variable definition. Have you any docs on this?

2023-03-15 16:58 UTC, DavidFee-UL commented on TF_Service_dotNet/TouchFree/TouchFreeLib.csproj
> +	</ItemGroup>
Ah I think I see: '$(PlatformTarget)'=='ARM64' and '$(PlatformTarget)'!='ARM64' seem redundant. So merge into a single group.

2023-03-16 08:53 UTC, GabrielHomewoodUL commented on TF_Service_dotNet/TouchFree/TouchFreeLib.csproj
> +	</ItemGroup>
I've added this as a placeholder for the x64 libs, so we can just add them and update the folder that the `$(PlatformTarget)!=ARM64` group points at

2023-03-16 09:04 UTC, DavidFee-UL commented on TF_Service_dotNet/TouchFree/TouchFreeLib.csproj
> +	</ItemGroup>
Got you.

2023-03-16 09:04 UTC, DavidFee-UL approved these changes

2023-03-16 09:07 UTC, merged